
services:
  mongodb:
    image: mongo:6
    container_name: party-paradise-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - party-paradise-network

  backend:
    build: ./backend
    container_name: party-paradise-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/party-paradise
      - PORT=5000
      - JWT_SECRET=party_paradise_jwt_secret_2024
      - RAZORPAY_KEY_ID=your_razorpay_key
      - RAZORPAY_KEY_SECRET=your_razorpay_secret
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASSWORD=your_app_password
      - FRONTEND_URL=http://localhost
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - party-paradise-network

  frontend:
    build: ./frontend
    container_name: party-paradise-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - party-paradise-network

volumes:
  mongodb_data:

networks:
  party-paradise-network:
    driver: bridge